# Generated by Django 3.2 on 2022-07-23 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=16, verbose_name='카드번호 16자리')),
                ('valid_date', models.CharField(max_length=4, verbose_name='유효기간 4자리(MM/YY)')),
                ('cvc', models.CharField(max_length=3, verbose_name='보안코드 3자리')),
                ('birth_date', models.CharField(max_length=6, verbose_name='생년월일 6자리')),
                ('password', models.CharField(max_length=2, verbose_name='비밀번호 앞 2자리')),
                ('is_agreed', models.BooleanField(verbose_name='개인정보 제공 동의')),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.serviceuser', verbose_name='서비스 유저')),
            ],
            options={
                'verbose_name': '카드',
                'verbose_name_plural': '카드들',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_user', models.CharField(max_length=255, verbose_name='서비스 유저')),
                ('pg', models.CharField(max_length=100, verbose_name='pg사')),
                ('method', models.CharField(choices=[('PRE', '선불'), ('DEFERRED', '후불')], max_length=100, verbose_name='결제방법')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.card', verbose_name='결제카드')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제들',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('used_point', models.PositiveBigIntegerField(default=0, verbose_name='사용 포인트')),
                ('is_delete', models.BooleanField(default=False, verbose_name='삭제')),
                ('charge_history', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stations.chargehistory', verbose_name='충전 기록')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.payment', verbose_name='결제')),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.serviceuser', verbose_name='서비스 유저')),
            ],
            options={
                'verbose_name': '결제 기록',
                'verbose_name_plural': '결제 기록들',
                'ordering': ('-id',),
            },
        ),
    ]
