# Generated by Django 3.2 on 2022-07-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_pointhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointhistory',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='삭제'),
        ),
    ]
