# Generated by Django 3.2 on 2022-07-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_pointhistory_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointhistory',
            old_name='amount',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='receipt_id',
            field=models.CharField(default=1, max_length=32, verbose_name='결제번호'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='state',
            field=models.CharField(choices=[('ready', '결제대기'), ('paid', '결제완료'), ('failed', '결제실패')], default='ready', max_length=100, verbose_name='결제방법'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('pre', '선불'), ('deferred', '후불')], max_length=100, verbose_name='결제방법'),
        ),
    ]
