# Generated by Django 3.2 on 2022-07-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20220723_1438'),
        ('payments', '0004_auto_20220723_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='charge_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stations.chargehistory', verbose_name='충전 기록'),
        ),
    ]
