# Generated by Django 3.2 on 2022-07-23 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymenthistory_charge_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='point_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.pointhistory', verbose_name='포인트 기록'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='receipt_id',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='결제번호'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='used_point',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True, verbose_name='사용 포인트'),
        ),
    ]
