# Generated by Django 3.2 on 2022-07-23 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('point', models.PositiveBigIntegerField(verbose_name='포인트')),
                ('expired_at', models.DateTimeField()),
                ('is_delete', models.BooleanField(default=False, verbose_name='삭제')),
            ],
            options={
                'verbose_name': '쿠폰',
                'verbose_name_plural': '쿠폰들',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CouponCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(choices=[('SIGNUP', '회원가입발급'), ('EVENT', '이벤트발급')], max_length=100, verbose_name='라벨')),
                ('code', models.CharField(max_length=100, verbose_name='코드')),
            ],
            options={
                'verbose_name': '쿠폰 카테고리',
                'verbose_name_plural': '쿠폰 카테고리들',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CouponHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False, verbose_name='삭제')),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='coupons.coupon')),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.serviceuser', verbose_name='서비스 유저')),
            ],
            options={
                'verbose_name': '쿠폰 기록',
                'verbose_name_plural': '쿠폰 기록들',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coupons.couponcategory', verbose_name='카테고리'),
        ),
    ]
