# Generated by Django 3.2 on 2022-07-23 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='expired_at',
        ),
    ]
