# Generated by Django 3.2 on 2022-07-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_remove_coupon_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcategory',
            name='label',
            field=models.CharField(choices=[('signup', '회원가입발급'), ('event', '이벤트발급')], max_length=100, verbose_name='라벨'),
        ),
    ]
