# Generated by Django 3.2 on 2022-07-23 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('battery_type', models.CharField(choices=[('LITHIUM-ION', '리튬이온 배터리'), ('NICKEL-METAL', '니켈메탈 배터리')], max_length=100, verbose_name='배터리 타입')),
                ('state', models.CharField(choices=[('USEABLE', '사용가능'), ('OCCUPIED', '사용중'), ('UNUSEABLE', '사용불가능')], max_length=100, verbose_name='상태')),
                ('address', models.CharField(max_length=200, verbose_name='주소')),
                ('lat', models.CharField(max_length=180, verbose_name='위도')),
                ('lng', models.CharField(max_length=180, verbose_name='경도')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='1kw 요금')),
            ],
            options={
                'verbose_name': '충전소',
                'verbose_name_plural': '충전소들',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ChargeHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트날짜')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='충전량')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='충전비용')),
                ('is_delete', models.BooleanField(default=False, verbose_name='삭제')),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.serviceuser', verbose_name='서비스 유저')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stations.station', verbose_name='충전소')),
            ],
            options={
                'verbose_name': '충전 기록',
                'verbose_name_plural': '충전 기록들',
                'ordering': ('-id',),
            },
        ),
    ]
