# Generated by Django 3.2 on 2022-07-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='battery_type',
            field=models.CharField(choices=[('lithium-ion', '리튬이온 배터리'), ('nickel-metal', '니켈메탈 배터리')], max_length=100, verbose_name='배터리 타입'),
        ),
        migrations.AlterField(
            model_name='station',
            name='state',
            field=models.CharField(choices=[('useable', '사용가능'), ('occupied', '사용중'), ('unuseable', '사용불가능')], max_length=100, verbose_name='상태'),
        ),
    ]
